### PR TITLE
add support for use collections

### PR DESCRIPTION
**Pull request by OtavioCostaLima**
Support like laravel collections!

### CODE REVIEW

**Comment by harrygulliford** [comment]
Could you please provide some more information about what this PR achieves?

**Comment by OtavioCostaLima** [comment]
> Could you please provide some more information about what this PR achieves?

This will support laravel collections as it currently doesn't!

**Comment by harrygulliford** [comment]
@OtavioCostaLima Thanks! Could you please provide a code example?

**Comment by OtavioCostaLima** [comment]
> @OtavioCostaLima Thanks! Could you please provide a code example?

`$model = new User;

$id = 1;

$user = $model->find($id);

$users = $model->where('status', true)->get();
`

**Comment by OtavioCostaLima** [comment]
> @OtavioCostaLima Thanks! Could you please provide a code example?

`$model = new User;`
`$id = 1;`
`$user = $model->find($id);`
`$users = $model->where('status', true)->get();`

**Comment by harrygulliford** [comment]
Changing `wrapValue()` method has the side effect of returning any unwrapped select aliases to uppercase, and this would therefore be a breaking change. 

```php
Device::select('DEVICEID as id')->where('DEVICEID', 1)->first();

// before: 
App\Device {
    id: 1
}

// after: 
App\Device {
    ID: 1,
}
```


I can see the benefit of being able to query using lowercase column names, and this is something I will likely look at in a future version.

For now, please use uppercase column names.

**Comment by OtavioCostaLima** [comment]
in `config/database.php` add the option CASE_LOWER in the database settings, Example:

         'firebird' => [
             'driver' => 'firebird',
             'host' => env('DB_HOST', ''),
             'database' => env('DB_DATABASE', ''),
             'username' => env('DB_USERNAME', ''),
             'password' => env('DB_PASSWORD', ''),
             'charset' => env('DB_CHARSET', ''),
             'version' => env('DB_VERSION', '2.5'),
             'roll' => null,
             'options' => array(
                 PDO::ATTR_CASE => PDO::CASE_LOWER,
             ),
         ],

**Pull request closed without merging**
